using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using PokemonReview.Models;

namespace PokemonReview
{
    public class DataContext : IdentityDbContext<AppUser>
    {
        //constructor
        public DataContext(DbContextOptions<DataContext> options) : base(options)
        {

        }

        //DbSets
        public DbSet<Category> Categories { get; set; }
        public DbSet<Pokemon> Pokemon { get; set; }
        public DbSet<PokemonCategory> PokemonCategories { get; set; }
        public DbSet<Reviews> Reviews { get; set; }


        //OnModelCreating
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //calls base implementation
            base.OnModelCreating(modelBuilder);

            //seed identity role data
            List<IdentityRole> roles = new List<IdentityRole>
            {
                new IdentityRole
                {
                    Name = "Admin",
                    NormalizedName = "ADMIN"
                },
                new IdentityRole
                {
                    Name = "User",
                    NormalizedName = "USER"
                },
            };
            modelBuilder.Entity<IdentityRole>().HasData(roles);

            //pokemon categories relationship
            modelBuilder.Entity<PokemonCategory>()
                    .HasKey(pc => new { pc.PokemonId, pc.CategoryId });
            modelBuilder.Entity<PokemonCategory>()
                    .HasOne(p => p.Pokemon)
                    .WithMany(pc => pc.PokemonCategories)
                    .HasForeignKey(p => p.PokemonId);
            modelBuilder.Entity<PokemonCategory>()
                    .HasOne(p => p.Category)
                    .WithMany(pc => pc.PokemonCategories)
                    .HasForeignKey(c => c.CategoryId);

            // Seed categories
            modelBuilder.Entity<Category>().HasData(
                new Category { Id = 1, Name = "Grass" },
                new Category { Id = 2, Name = "Poison" },
                new Category { Id = 3, Name = "Fire" },
                new Category { Id = 4, Name = "Flying" },
                new Category { Id = 5, Name = "Water" },
                new Category { Id = 6, Name = "Bug" },
                new Category { Id = 7, Name = "Normal" },
                new Category { Id = 8, Name = "Electric" },
                new Category { Id = 9, Name = "Ground" },
                new Category { Id = 10, Name = "Fighting" },
                new Category { Id = 11, Name = "Psychic" },
                new Category { Id = 12, Name = "Rock" },
                new Category { Id = 13, Name = "Ice" },
                new Category { Id = 14, Name = "Ghost" },
                new Category { Id = 15, Name = "Dragon" }
            );

            // Seed Pokémon
            modelBuilder.Entity<Pokemon>().HasData(
                new Pokemon { Id = 1, Name = "Bulbasaur" },
                new Pokemon { Id = 2, Name = "Ivysaur" },
                new Pokemon { Id = 3, Name = "Venusaur" },
                new Pokemon { Id = 4, Name = "Charmander" },
                new Pokemon { Id = 5, Name = "Charmeleon" },
                new Pokemon { Id = 6, Name = "Charizard" },
                new Pokemon { Id = 7, Name = "Squirtle" },
                new Pokemon { Id = 8, Name = "Wartortle" },
                new Pokemon { Id = 9, Name = "Blastoise" },
                new Pokemon { Id = 10, Name = "Caterpie" },
                new Pokemon { Id = 11, Name = "Metapod" },
                new Pokemon { Id = 12, Name = "Butterfree" },
                new Pokemon { Id = 13, Name = "Weedle" },
                new Pokemon { Id = 14, Name = "Kakuna" },
                new Pokemon { Id = 15, Name = "Beedrill" },
                new Pokemon { Id = 16, Name = "Pidgey" },
                new Pokemon { Id = 17, Name = "Pidgeotto" },
                new Pokemon { Id = 18, Name = "Pidgeot" },
                new Pokemon { Id = 19, Name = "Rattata" },
                new Pokemon { Id = 20, Name = "Raticate" },
                new Pokemon { Id = 21, Name = "Spearow" },
                new Pokemon { Id = 22, Name = "Fearow" },
                new Pokemon { Id = 23, Name = "Ekans" },
                new Pokemon { Id = 24, Name = "Arbok" },
                new Pokemon { Id = 25, Name = "Pikachu" },
                new Pokemon { Id = 26, Name = "Raichu" },
                new Pokemon { Id = 27, Name = "Sandshrew" },
                new Pokemon { Id = 28, Name = "Sandslash" },
                new Pokemon { Id = 29, Name = "Nidoran♀" },
                new Pokemon { Id = 30, Name = "Nidorina" },
                new Pokemon { Id = 31, Name = "Nidoqueen" },
                new Pokemon { Id = 32, Name = "Nidoran♂" },
                new Pokemon { Id = 33, Name = "Nidorino" },
                new Pokemon { Id = 34, Name = "Nidoking" },
                new Pokemon { Id = 35, Name = "Clefairy" },
                new Pokemon { Id = 36, Name = "Clefable" },
                new Pokemon { Id = 37, Name = "Vulpix" },
                new Pokemon { Id = 38, Name = "Ninetales" },
                new Pokemon { Id = 39, Name = "Jigglypuff" },
                new Pokemon { Id = 40, Name = "Wigglytuff" },
                new Pokemon { Id = 41, Name = "Zubat" },
                new Pokemon { Id = 42, Name = "Golbat" },
                new Pokemon { Id = 43, Name = "Oddish" },
                new Pokemon { Id = 44, Name = "Gloom" },
                new Pokemon { Id = 45, Name = "Vileplume" },
                new Pokemon { Id = 46, Name = "Paras" },
                new Pokemon { Id = 47, Name = "Parasect" },
                new Pokemon { Id = 48, Name = "Venonat" },
                new Pokemon { Id = 49, Name = "Venomoth" },
                new Pokemon { Id = 50, Name = "Diglett" },
                new Pokemon { Id = 51, Name = "Dugtrio" },
                new Pokemon { Id = 52, Name = "Meowth" },
                new Pokemon { Id = 53, Name = "Persian" },
                new Pokemon { Id = 54, Name = "Psyduck" },
                new Pokemon { Id = 55, Name = "Golduck" },
                new Pokemon { Id = 56, Name = "Mankey" },
                new Pokemon { Id = 57, Name = "Primeape" },
                new Pokemon { Id = 58, Name = "Growlithe" },
                new Pokemon { Id = 59, Name = "Arcanine" },
                new Pokemon { Id = 60, Name = "Poliwag" },
                new Pokemon { Id = 61, Name = "Poliwhirl" },
                new Pokemon { Id = 62, Name = "Poliwrath" },
                new Pokemon { Id = 63, Name = "Abra" },
                new Pokemon { Id = 64, Name = "Kadabra" },
                new Pokemon { Id = 65, Name = "Alakazam" },
                new Pokemon { Id = 66, Name = "Machop" },
                new Pokemon { Id = 67, Name = "Machoke" },
                new Pokemon { Id = 68, Name = "Machamp" },
                new Pokemon { Id = 69, Name = "Bellsprout" },
                new Pokemon { Id = 70, Name = "Weepinbell" },
                new Pokemon { Id = 71, Name = "Victreebel" },
                new Pokemon { Id = 72, Name = "Tentacool" },
                new Pokemon { Id = 73, Name = "Tentacruel" },
                new Pokemon { Id = 74, Name = "Geodude" },
                new Pokemon { Id = 75, Name = "Graveler" },
                new Pokemon { Id = 76, Name = "Golem" },
                new Pokemon { Id = 77, Name = "Ponyta" },
                new Pokemon { Id = 78, Name = "Rapidash" },
                new Pokemon { Id = 79, Name = "Slowpoke" },
                new Pokemon { Id = 80, Name = "Slowbro" },
                new Pokemon { Id = 81, Name = "Magnemite" },
                new Pokemon { Id = 82, Name = "Magneton" },
                new Pokemon { Id = 83, Name = "Farfetch'd" },
                new Pokemon { Id = 84, Name = "Doduo" },
                new Pokemon { Id = 85, Name = "Dodrio" },
                new Pokemon { Id = 86, Name = "Seel" },
                new Pokemon { Id = 87, Name = "Dewgong" },
                new Pokemon { Id = 88, Name = "Grimer" },
                new Pokemon { Id = 89, Name = "Muk" },
                new Pokemon { Id = 90, Name = "Shellder" },
                new Pokemon { Id = 91, Name = "Cloyster" },
                new Pokemon { Id = 92, Name = "Gastly" },
                new Pokemon { Id = 93, Name = "Haunter" },
                new Pokemon { Id = 94, Name = "Gengar" },
                new Pokemon { Id = 95, Name = "Onix" },
                new Pokemon { Id = 96, Name = "Drowzee" },
                new Pokemon { Id = 97, Name = "Hypno" },
                new Pokemon { Id = 98, Name = "Krabby" },
                new Pokemon { Id = 99, Name = "Kingler" },
                new Pokemon { Id = 100, Name = "Voltorb" },
                new Pokemon { Id = 101, Name = "Electrode" },
                new Pokemon { Id = 102, Name = "Exeggcute" },
                new Pokemon { Id = 103, Name = "Exeggutor" },
                new Pokemon { Id = 104, Name = "Cubone" },
                new Pokemon { Id = 105, Name = "Marowak" },
                new Pokemon { Id = 106, Name = "Hitmonlee" },
                new Pokemon { Id = 107, Name = "Hitmonchan" },
                new Pokemon { Id = 108, Name = "Lickitung" },
                new Pokemon { Id = 109, Name = "Koffing" },
                new Pokemon { Id = 110, Name = "Weezing" },
                new Pokemon { Id = 111, Name = "Rhyhorn" },
                new Pokemon { Id = 112, Name = "Rhydon" },
                new Pokemon { Id = 113, Name = "Chansey" },
                new Pokemon { Id = 114, Name = "Tangela" },
                new Pokemon { Id = 115, Name = "Kangaskhan" },
                new Pokemon { Id = 116, Name = "Horsea" },
                new Pokemon { Id = 117, Name = "Seadra" },
                new Pokemon { Id = 118, Name = "Goldeen" },
                new Pokemon { Id = 119, Name = "Seaking" },
                new Pokemon { Id = 120, Name = "Staryu" },
                new Pokemon { Id = 121, Name = "Starmie" },
                new Pokemon { Id = 122, Name = "Mr.Mime" },
                new Pokemon { Id = 123, Name = "Scyther" },
                new Pokemon { Id = 124, Name = "Jynx" },
                new Pokemon { Id = 125, Name = "Electabuzz" },
                new Pokemon { Id = 126, Name = "Magmar" },
                new Pokemon { Id = 127, Name = "Pinsir" },
                new Pokemon { Id = 128, Name = "Tauros" },
                new Pokemon { Id = 129, Name = "Magikarp" },
                new Pokemon { Id = 130, Name = "Gyarados" },
                new Pokemon { Id = 131, Name = "Lapras" },
                new Pokemon { Id = 132, Name = "Ditto" },
                new Pokemon { Id = 133, Name = "Eevee" },
                new Pokemon { Id = 134, Name = "Vaporeon" },
                new Pokemon { Id = 135, Name = "Jolteon" },
                new Pokemon { Id = 136, Name = "Flareon" },
                new Pokemon { Id = 137, Name = "Porygon" },
                new Pokemon { Id = 138, Name = "Omanyte" },
                new Pokemon { Id = 139, Name = "Omastar" },
                new Pokemon { Id = 140, Name = "Kabuto" },
                new Pokemon { Id = 141, Name = "Kabutops" },
                new Pokemon { Id = 142, Name = "Aerodactyl" },
                new Pokemon { Id = 143, Name = "Snorlax" },
                new Pokemon { Id = 144, Name = "Articuno" },
                new Pokemon { Id = 145, Name = "Zapdos" },
                new Pokemon { Id = 146, Name = "Moltres" },
                new Pokemon { Id = 147, Name = "Dratini" },
                new Pokemon { Id = 148, Name = "Dragonair" },
                new Pokemon { Id = 149, Name = "Dragonite" },
                new Pokemon { Id = 150, Name = "Mewtwo" },
                new Pokemon { Id = 151, Name = "Mew" }
            );

            // Seed the PokemonCategory many-to-many relationship
            modelBuilder.Entity<PokemonCategory>().HasData(
            new PokemonCategory { PokemonId = 1, CategoryId = 1 },
                new PokemonCategory { PokemonId = 2, CategoryId = 1 },
                new PokemonCategory { PokemonId = 3, CategoryId = 1 },
                new PokemonCategory { PokemonId = 4, CategoryId = 3 },
                new PokemonCategory { PokemonId = 5, CategoryId = 3 },
                new PokemonCategory { PokemonId = 6, CategoryId = 3 },
                new PokemonCategory { PokemonId = 7, CategoryId = 5 },
                new PokemonCategory { PokemonId = 8, CategoryId = 5 },
                new PokemonCategory { PokemonId = 9, CategoryId = 5 },
                new PokemonCategory { PokemonId = 10, CategoryId = 6 },
                new PokemonCategory { PokemonId = 11, CategoryId = 6 },
                new PokemonCategory { PokemonId = 12, CategoryId = 6 },
                new PokemonCategory { PokemonId = 13, CategoryId = 6 },
                new PokemonCategory { PokemonId = 14, CategoryId = 6 },
                new PokemonCategory { PokemonId = 15, CategoryId = 6 },
                new PokemonCategory { PokemonId = 16, CategoryId = 7 },
                new PokemonCategory { PokemonId = 17, CategoryId = 7 },
                new PokemonCategory { PokemonId = 18, CategoryId = 7 },
                new PokemonCategory { PokemonId = 19, CategoryId = 7 },
                new PokemonCategory { PokemonId = 20, CategoryId = 7 },
                new PokemonCategory { PokemonId = 21, CategoryId = 7 },
                new PokemonCategory { PokemonId = 22, CategoryId = 7 },
                new PokemonCategory { PokemonId = 23, CategoryId = 2 },
                new PokemonCategory { PokemonId = 24, CategoryId = 2 },
                new PokemonCategory { PokemonId = 25, CategoryId = 8 },
                new PokemonCategory { PokemonId = 26, CategoryId = 8 },
                new PokemonCategory { PokemonId = 27, CategoryId = 9 },
                new PokemonCategory { PokemonId = 28, CategoryId = 9 },
                new PokemonCategory { PokemonId = 29, CategoryId = 2 },
                new PokemonCategory { PokemonId = 30, CategoryId = 2 },
                new PokemonCategory { PokemonId = 31, CategoryId = 2 },
                new PokemonCategory { PokemonId = 32, CategoryId = 2 },
                new PokemonCategory { PokemonId = 33, CategoryId = 2 },
                new PokemonCategory { PokemonId = 34, CategoryId = 2 },
                new PokemonCategory { PokemonId = 35, CategoryId = 7 },
                new PokemonCategory { PokemonId = 36, CategoryId = 7 },
                new PokemonCategory { PokemonId = 37, CategoryId = 3 },
                new PokemonCategory { PokemonId = 38, CategoryId = 3 },
                new PokemonCategory { PokemonId = 39, CategoryId = 7 },
                new PokemonCategory { PokemonId = 40, CategoryId = 7 },
                new PokemonCategory { PokemonId = 41, CategoryId = 2 },
                new PokemonCategory { PokemonId = 42, CategoryId = 2 },
                new PokemonCategory { PokemonId = 43, CategoryId = 1 },
                new PokemonCategory { PokemonId = 44, CategoryId = 1 },
                new PokemonCategory { PokemonId = 45, CategoryId = 1 },
                new PokemonCategory { PokemonId = 46, CategoryId = 6 },
                new PokemonCategory { PokemonId = 47, CategoryId = 6 },
                new PokemonCategory { PokemonId = 48, CategoryId = 6 },
                new PokemonCategory { PokemonId = 49, CategoryId = 6 },
                new PokemonCategory { PokemonId = 50, CategoryId = 9 },
                new PokemonCategory { PokemonId = 51, CategoryId = 9 },
                new PokemonCategory { PokemonId = 52, CategoryId = 7 },
                new PokemonCategory { PokemonId = 53, CategoryId = 7 },
                new PokemonCategory { PokemonId = 54, CategoryId = 5 },
                new PokemonCategory { PokemonId = 55, CategoryId = 5 },
                new PokemonCategory { PokemonId = 56, CategoryId = 10 },
                new PokemonCategory { PokemonId = 57, CategoryId = 10 },
                new PokemonCategory { PokemonId = 58, CategoryId = 3 },
                new PokemonCategory { PokemonId = 59, CategoryId = 3 },
                new PokemonCategory { PokemonId = 60, CategoryId = 5 },
                new PokemonCategory { PokemonId = 61, CategoryId = 5 },
                new PokemonCategory { PokemonId = 62, CategoryId = 5 },
                new PokemonCategory { PokemonId = 63, CategoryId = 11 },
                new PokemonCategory { PokemonId = 64, CategoryId = 11 },
                new PokemonCategory { PokemonId = 65, CategoryId = 11 },
                new PokemonCategory { PokemonId = 66, CategoryId = 10 },
                new PokemonCategory { PokemonId = 67, CategoryId = 10 },
                new PokemonCategory { PokemonId = 68, CategoryId = 10 },
                new PokemonCategory { PokemonId = 69, CategoryId = 1 },
                new PokemonCategory { PokemonId = 70, CategoryId = 1 },
                new PokemonCategory { PokemonId = 71, CategoryId = 1 },
                new PokemonCategory { PokemonId = 72, CategoryId = 5 },
                new PokemonCategory { PokemonId = 73, CategoryId = 5 },
                new PokemonCategory { PokemonId = 74, CategoryId = 12 },
                new PokemonCategory { PokemonId = 75, CategoryId = 12 },
                new PokemonCategory { PokemonId = 76, CategoryId = 12 },
                new PokemonCategory { PokemonId = 77, CategoryId = 3 },
                new PokemonCategory { PokemonId = 78, CategoryId = 3 },
                new PokemonCategory { PokemonId = 79, CategoryId = 5 },
                new PokemonCategory { PokemonId = 80, CategoryId = 5 },
                new PokemonCategory { PokemonId = 81, CategoryId = 8 },
                new PokemonCategory { PokemonId = 82, CategoryId = 8 },
                new PokemonCategory { PokemonId = 83, CategoryId = 7 },
                new PokemonCategory { PokemonId = 84, CategoryId = 7 },
                new PokemonCategory { PokemonId = 85, CategoryId = 7 },
                new PokemonCategory { PokemonId = 86, CategoryId = 5 },
                new PokemonCategory { PokemonId = 87, CategoryId = 5 },
                new PokemonCategory { PokemonId = 88, CategoryId = 2 },
                new PokemonCategory { PokemonId = 89, CategoryId = 2 },
                new PokemonCategory { PokemonId = 90, CategoryId = 5 },
                new PokemonCategory { PokemonId = 91, CategoryId = 5 },
                new PokemonCategory { PokemonId = 92, CategoryId = 14 },
                new PokemonCategory { PokemonId = 93, CategoryId = 14 },
                new PokemonCategory { PokemonId = 94, CategoryId = 14 },
                new PokemonCategory { PokemonId = 95, CategoryId = 12 },
                new PokemonCategory { PokemonId = 96, CategoryId = 11 },
                new PokemonCategory { PokemonId = 97, CategoryId = 11 },
                new PokemonCategory { PokemonId = 98, CategoryId = 5 },
                new PokemonCategory { PokemonId = 99, CategoryId = 5 },
                new PokemonCategory { PokemonId = 100, CategoryId = 8 },
                new PokemonCategory { PokemonId = 101, CategoryId = 8 },
                new PokemonCategory { PokemonId = 102, CategoryId = 1 },
                new PokemonCategory { PokemonId = 103, CategoryId = 1 },
                new PokemonCategory { PokemonId = 104, CategoryId = 9 },
                new PokemonCategory { PokemonId = 105, CategoryId = 9 },
                new PokemonCategory { PokemonId = 106, CategoryId = 10 },
                new PokemonCategory { PokemonId = 107, CategoryId = 10 },
                new PokemonCategory { PokemonId = 108, CategoryId = 7 },
                new PokemonCategory { PokemonId = 109, CategoryId = 2 },
                new PokemonCategory { PokemonId = 110, CategoryId = 2 },
                new PokemonCategory { PokemonId = 111, CategoryId = 9 },
                new PokemonCategory { PokemonId = 112, CategoryId = 9 },
                new PokemonCategory { PokemonId = 113, CategoryId = 7 },
                new PokemonCategory { PokemonId = 114, CategoryId = 1 },
                new PokemonCategory { PokemonId = 115, CategoryId = 7 },
                new PokemonCategory { PokemonId = 116, CategoryId = 5 },
                new PokemonCategory { PokemonId = 117, CategoryId = 5 },
                new PokemonCategory { PokemonId = 118, CategoryId = 5 },
                new PokemonCategory { PokemonId = 119, CategoryId = 5 },
                new PokemonCategory { PokemonId = 120, CategoryId = 5 },
                new PokemonCategory { PokemonId = 121, CategoryId = 5 },
                new PokemonCategory { PokemonId = 122, CategoryId = 11 },
                new PokemonCategory { PokemonId = 123, CategoryId = 6 },
                new PokemonCategory { PokemonId = 124, CategoryId = 13 },
                new PokemonCategory { PokemonId = 125, CategoryId = 8 },
                new PokemonCategory { PokemonId = 126, CategoryId = 3 },
                new PokemonCategory { PokemonId = 127, CategoryId = 6 },
                new PokemonCategory { PokemonId = 128, CategoryId = 7 },
                new PokemonCategory { PokemonId = 129, CategoryId = 5 },
                new PokemonCategory { PokemonId = 130, CategoryId = 5 },
                new PokemonCategory { PokemonId = 131, CategoryId = 5 },
                new PokemonCategory { PokemonId = 132, CategoryId = 7 },
                new PokemonCategory { PokemonId = 133, CategoryId = 7 },
                new PokemonCategory { PokemonId = 134, CategoryId = 5 },
                new PokemonCategory { PokemonId = 135, CategoryId = 8 },
                new PokemonCategory { PokemonId = 136, CategoryId = 3 },
                new PokemonCategory { PokemonId = 137, CategoryId = 7 },
                new PokemonCategory { PokemonId = 138, CategoryId = 12 },
                new PokemonCategory { PokemonId = 139, CategoryId = 12 },
                new PokemonCategory { PokemonId = 140, CategoryId = 12 },
                new PokemonCategory { PokemonId = 141, CategoryId = 12 },
                new PokemonCategory { PokemonId = 142, CategoryId = 12 },
                new PokemonCategory { PokemonId = 143, CategoryId = 7 },
                new PokemonCategory { PokemonId = 144, CategoryId = 13 },
                new PokemonCategory { PokemonId = 145, CategoryId = 8 },
                new PokemonCategory { PokemonId = 146, CategoryId = 3 },
                new PokemonCategory { PokemonId = 147, CategoryId = 15 },
                new PokemonCategory { PokemonId = 148, CategoryId = 15 },
                new PokemonCategory { PokemonId = 149, CategoryId = 15 },
                new PokemonCategory { PokemonId = 150, CategoryId = 11 },
                new PokemonCategory { PokemonId = 151, CategoryId = 11 },
                new PokemonCategory { PokemonId = 1, CategoryId = 2 },
                new PokemonCategory { PokemonId = 2, CategoryId = 2 },
                new PokemonCategory { PokemonId = 3, CategoryId = 2 },
                new PokemonCategory { PokemonId = 6, CategoryId = 4 },
                new PokemonCategory { PokemonId = 12, CategoryId = 4 },
                new PokemonCategory { PokemonId = 13, CategoryId = 2 },
                new PokemonCategory { PokemonId = 14, CategoryId = 2 },
                new PokemonCategory { PokemonId = 15, CategoryId = 2 },
                new PokemonCategory { PokemonId = 16, CategoryId = 4 },
                new PokemonCategory { PokemonId = 17, CategoryId = 4 },
                new PokemonCategory { PokemonId = 18, CategoryId = 4 },
                new PokemonCategory { PokemonId = 21, CategoryId = 4 },
                new PokemonCategory { PokemonId = 22, CategoryId = 4 },
                new PokemonCategory { PokemonId = 31, CategoryId = 9 },
                new PokemonCategory { PokemonId = 34, CategoryId = 9 },
                new PokemonCategory { PokemonId = 41, CategoryId = 4 },
                new PokemonCategory { PokemonId = 42, CategoryId = 4 },
                new PokemonCategory { PokemonId = 43, CategoryId = 2 },
                new PokemonCategory { PokemonId = 44, CategoryId = 2 },
                new PokemonCategory { PokemonId = 45, CategoryId = 2 },
                new PokemonCategory { PokemonId = 46, CategoryId = 1 },
                new PokemonCategory { PokemonId = 47, CategoryId = 1 },
                new PokemonCategory { PokemonId = 48, CategoryId = 2 },
                new PokemonCategory { PokemonId = 49, CategoryId = 2 },
                new PokemonCategory { PokemonId = 62, CategoryId = 10 },
                new PokemonCategory { PokemonId = 69, CategoryId = 2 },
                new PokemonCategory { PokemonId = 70, CategoryId = 2 },
                new PokemonCategory { PokemonId = 71, CategoryId = 2 },
                new PokemonCategory { PokemonId = 72, CategoryId = 2 },
                new PokemonCategory { PokemonId = 73, CategoryId = 2 },
                new PokemonCategory { PokemonId = 74, CategoryId = 9 },
                new PokemonCategory { PokemonId = 75, CategoryId = 9 },
                new PokemonCategory { PokemonId = 76, CategoryId = 9 },
                new PokemonCategory { PokemonId = 79, CategoryId = 11 },
                new PokemonCategory { PokemonId = 80, CategoryId = 11 },
                new PokemonCategory { PokemonId = 83, CategoryId = 4 },
                new PokemonCategory { PokemonId = 84, CategoryId = 4 },
                new PokemonCategory { PokemonId = 85, CategoryId = 4 },
                new PokemonCategory { PokemonId = 87, CategoryId = 13 },
                new PokemonCategory { PokemonId = 91, CategoryId = 13 },
                new PokemonCategory { PokemonId = 92, CategoryId = 2 },
                new PokemonCategory { PokemonId = 93, CategoryId = 2 },
                new PokemonCategory { PokemonId = 94, CategoryId = 2 },
                new PokemonCategory { PokemonId = 95, CategoryId = 9 },
                new PokemonCategory { PokemonId = 102, CategoryId = 11 },
                new PokemonCategory { PokemonId = 103, CategoryId = 11 },
                new PokemonCategory { PokemonId = 111, CategoryId = 12 },
                new PokemonCategory { PokemonId = 112, CategoryId = 12 },
                new PokemonCategory { PokemonId = 121, CategoryId = 11 },
                new PokemonCategory { PokemonId = 123, CategoryId = 4 },
                new PokemonCategory { PokemonId = 124, CategoryId = 11 },
                new PokemonCategory { PokemonId = 130, CategoryId = 4 },
                new PokemonCategory { PokemonId = 131, CategoryId = 13 },
                new PokemonCategory { PokemonId = 138, CategoryId = 5 },
                new PokemonCategory { PokemonId = 139, CategoryId = 5 },
                new PokemonCategory { PokemonId = 140, CategoryId = 5 },
                new PokemonCategory { PokemonId = 141, CategoryId = 5 },
                new PokemonCategory { PokemonId = 142, CategoryId = 4 },
                new PokemonCategory { PokemonId = 144, CategoryId = 4 },
                new PokemonCategory { PokemonId = 145, CategoryId = 4 },
                new PokemonCategory { PokemonId = 146, CategoryId = 4 },
                new PokemonCategory { PokemonId = 149, CategoryId = 4 }   
            );
        }
    }
}
