using PokemonReview.Models;

namespace PokemonReview
{
    public class SeedData
    {
        private readonly DataContext dataContext;
        public SeedData(DataContext context)
        {
            dataContext = context;
        }
        public void SeedDataContext()
        {
            {
                // Check to see if data exists
                if (dataContext.Pokemon.Any() || dataContext.Categories.Any())
                {
                    return; // Data already exists, no data added
                }

                // Else seed data
                // Seed Categories
                var categories = new Category[]
                {
                new Category { Name = "Grass" },
                new Category { Name = "Poison" },
                new Category { Name = "Fire" },
                new Category { Name = "Flying" },
                new Category { Name = "Water" },
                new Category { Name = "Bug" },
                new Category { Name = "Normal" },
                new Category { Name = "Electric" },
                new Category { Name = "Ground" },
                new Category { Name = "Fighting" },
                new Category { Name = "Psychic" },
                new Category { Name = "Rock" },
                new Category { Name = "Ice" },
                new Category { Name = "Ghost" },
                new Category { Name = "Dragon" },
                    // Add more categories as needed
                };
                dataContext.Categories.AddRange(categories);

                // Seed Pokemon
                var pokemons = new Pokemon[]
                {
                new Pokemon { Name = "Bulbasaur"},
                new Pokemon { Name = "Ivysaur" },
                new Pokemon { Name = "Venusaur" },
                new Pokemon { Name = "Charmander" },
                new Pokemon { Name = "Charmeleon" },
                new Pokemon { Name = "Charizard" },
                new Pokemon { Name = "Squirtle" },
                new Pokemon { Name = "Wartortle" },
                new Pokemon { Name = "Blastoise" },
                new Pokemon { Name = "Caterpie" },
                new Pokemon { Name = "Metapod" },
                new Pokemon { Name = "Butterfree" },
                new Pokemon { Name = "Weedle" },
                new Pokemon { Name = "Kakuna" },
                new Pokemon { Name = "Beedrill" },
                new Pokemon { Name = "Pidgey" },
                new Pokemon { Name = "Pidgeotto" },
                new Pokemon { Name = "Pidgeot" },
                new Pokemon { Name = "Rattata" },
                new Pokemon { Name = "Raticate" },
                new Pokemon { Name = "Spearow" },
                new Pokemon { Name = "Fearow" },
                new Pokemon { Name = "Ekans" },
                new Pokemon { Name = "Arbok" },
                new Pokemon { Name = "Pikachu" },
                new Pokemon { Name = "Raichu" },
                new Pokemon { Name = "Sandshrew" },
                new Pokemon { Name = "Sandslash" },
                new Pokemon { Name = "Nidoran♀" },
                new Pokemon { Name = "Nidorina" },
                new Pokemon { Name = "Nidoqueen" },
                new Pokemon { Name = "Nidoran♂" },
                new Pokemon { Name = "Nidorino" },
                new Pokemon { Name = "Nidoking" },
                new Pokemon { Name = "Clefairy" },
                new Pokemon { Name = "Clefable" },
                new Pokemon { Name = "Vulpix" },
                new Pokemon { Name = "Ninetales" },
                new Pokemon { Name = "Jigglypuff" },
                new Pokemon { Name = "Wigglytuff" },
                new Pokemon { Name = "Zubat" },
                new Pokemon { Name = "Golbat" },
                new Pokemon { Name = "Oddish" },
                new Pokemon { Name = "Gloom" },
                new Pokemon { Name = "Vileplume" },
                new Pokemon { Name = "Paras" },
                new Pokemon { Name = "Parasect" },
                new Pokemon { Name = "Venonat" },
                new Pokemon { Name = "Venomoth" },
                new Pokemon { Name = "Diglett" },
                new Pokemon { Name = "Dugtrio" },
                new Pokemon { Name = "Meowth" },
                new Pokemon { Name = "Persian" },
                new Pokemon { Name = "Psyduck" },
                new Pokemon { Name = "Golduck" },
                new Pokemon { Name = "Mankey" },
                new Pokemon { Name = "Primeape" },
                new Pokemon { Name = "Growlithe" },
                new Pokemon { Name = "Arcanine" },
                new Pokemon { Name = "Poliwag" },
                new Pokemon { Name = "Poliwhirl" },
                new Pokemon { Name = "Poliwrath" },
                new Pokemon { Name = "Abra" },
                new Pokemon { Name = "Kadabra" },
                new Pokemon { Name = "Alakazam" },
                new Pokemon { Name = "Machop" },
                new Pokemon { Name = "Machoke" },
                new Pokemon { Name = "Machamp" },
                new Pokemon { Name = "Bellsprout" },
                new Pokemon { Name = "Weepinbell" },
                new Pokemon { Name = "Victreebel" },
                new Pokemon { Name = "Tentacool" },
                new Pokemon { Name = "Tentacruel" },
                new Pokemon { Name = "Geodude" },
                new Pokemon { Name = "Graveler" },
                new Pokemon { Name = "Golem" },
                new Pokemon { Name = "Ponyta" },
                new Pokemon { Name = "Rapidash" },
                new Pokemon { Name = "Slowpoke" },
                new Pokemon { Name = "Slowbro" },
                new Pokemon { Name = "Magnemite" },
                new Pokemon { Name = "Magneton" },
                new Pokemon { Name = "Farfetch'd" },
                new Pokemon { Name = "Doduo" },
                new Pokemon { Name = "Dodrio" },
                new Pokemon { Name = "Seel" },
                new Pokemon { Name = "Dewgong" },
                new Pokemon { Name = "Grimer" },
                new Pokemon { Name = "Muk" },
                new Pokemon { Name = "Shellder" },
                new Pokemon { Name = "Cloyster" },
                new Pokemon { Name = "Gastly" },
                new Pokemon { Name = "Haunter" },
                new Pokemon { Name = "Gengar" },
                new Pokemon { Name = "Onix" },
                new Pokemon { Name = "Drowzee" },
                new Pokemon { Name = "Hypno" },
                new Pokemon { Name = "Krabby" },
                new Pokemon { Name = "Kingler" },
                new Pokemon { Name = "Voltorb" },
                new Pokemon { Name = "Electrode" },
                new Pokemon { Name = "Exeggcute" },
                new Pokemon { Name = "Exeggutor" },
                new Pokemon { Name = "Cubone" },
                new Pokemon { Name = "Marowak" },
                new Pokemon { Name = "Hitmonlee" },
                new Pokemon { Name = "Hitmonchan" },
                new Pokemon { Name = "Lickitung" },
                new Pokemon { Name = "Koffing" },
                new Pokemon { Name = "Weezing" },
                new Pokemon { Name = "Rhyhorn" },
                new Pokemon { Name = "Rhydon" },
                new Pokemon { Name = "Chansey" },
                new Pokemon { Name = "Tangela" },
                new Pokemon { Name = "Kangaskhan" },
                new Pokemon { Name = "Horsea" },
                new Pokemon { Name = "Seadra" },
                new Pokemon { Name = "Goldeen" },
                new Pokemon { Name = "Seaking" },
                new Pokemon { Name = "Staryu" },
                new Pokemon { Name = "Starmie" },
                new Pokemon { Name = "Mr.Mime" },
                new Pokemon { Name = "Scyther" },
                new Pokemon { Name = "Jynx" },
                new Pokemon { Name = "Electabuzz" },
                new Pokemon { Name = "Magmar" },
                new Pokemon { Name = "Pinsir" },
                new Pokemon { Name = "Tauros" },
                new Pokemon { Name = "Magikarp" },
                new Pokemon { Name = "Gyarados" },
                new Pokemon { Name = "Lapras" },
                new Pokemon { Name = "Ditto" },
                new Pokemon { Name = "Eevee" },
                new Pokemon { Name = "Vaporeon" },
                new Pokemon { Name = "Jolteon" },
                new Pokemon { Name = "Flareon" },
                new Pokemon { Name = "Porygon" },
                new Pokemon { Name = "Omanyte" },
                new Pokemon { Name = "Omastar" },
                new Pokemon { Name = "Kabuto" },
                new Pokemon { Name = "Kabutops" },
                new Pokemon { Name = "Aerodactyl" },
                new Pokemon { Name = "Snorlax" },
                new Pokemon { Name = "Articuno" },
                new Pokemon { Name = "Zapdos" },
                new Pokemon { Name = "Moltres" },
                new Pokemon { Name = "Dratini" },
                new Pokemon { Name = "Dragonair" },
                new Pokemon { Name = "Dragonite" },
                new Pokemon { Name = "Mewtwo" },
                new Pokemon { Name = "Mew" }
                };
                dataContext.Pokemon.AddRange(pokemons);

                // Seed PokemonCategory relationships
                var pokemonCategories = new PokemonCategory[]
                {
                new PokemonCategory { PokemonId = 1, CategoryId = 1 },
                new PokemonCategory { PokemonId = 2, CategoryId = 1 },
                new PokemonCategory { PokemonId = 3, CategoryId = 1 },
                new PokemonCategory { PokemonId = 4, CategoryId = 3 },
                new PokemonCategory { PokemonId = 5, CategoryId = 3 },
                new PokemonCategory { PokemonId = 6, CategoryId = 3 },
                new PokemonCategory { PokemonId = 7, CategoryId = 5 },
                new PokemonCategory { PokemonId = 8, CategoryId = 5 },
                new PokemonCategory { PokemonId = 9, CategoryId = 5 },
                new PokemonCategory { PokemonId = 10, CategoryId = 6 },
                new PokemonCategory { PokemonId = 11, CategoryId = 6 },
                new PokemonCategory { PokemonId = 12, CategoryId = 6 },
                new PokemonCategory { PokemonId = 13, CategoryId = 6 },
                new PokemonCategory { PokemonId = 14, CategoryId = 6 },
                new PokemonCategory { PokemonId = 15, CategoryId = 6 },
                new PokemonCategory { PokemonId = 16, CategoryId = 7 },
                new PokemonCategory { PokemonId = 17, CategoryId = 7 },
                new PokemonCategory { PokemonId = 18, CategoryId = 7 },
                new PokemonCategory { PokemonId = 19, CategoryId = 7 },
                new PokemonCategory { PokemonId = 20, CategoryId = 7 },
                new PokemonCategory { PokemonId = 21, CategoryId = 7 },
                new PokemonCategory { PokemonId = 22, CategoryId = 7 },
                new PokemonCategory { PokemonId = 23, CategoryId = 2 },
                new PokemonCategory { PokemonId = 24, CategoryId = 2 },
                new PokemonCategory { PokemonId = 25, CategoryId = 8 },
                new PokemonCategory { PokemonId = 26, CategoryId = 8 },
                new PokemonCategory { PokemonId = 27, CategoryId = 9 },
                new PokemonCategory { PokemonId = 28, CategoryId = 9 },
                new PokemonCategory { PokemonId = 29, CategoryId = 2 },
                new PokemonCategory { PokemonId = 30, CategoryId = 2 },
                new PokemonCategory { PokemonId = 31, CategoryId = 2 },
                new PokemonCategory { PokemonId = 32, CategoryId = 2 },
                new PokemonCategory { PokemonId = 33, CategoryId = 2 },
                new PokemonCategory { PokemonId = 34, CategoryId = 2 },
                new PokemonCategory { PokemonId = 35, CategoryId = 7 },
                new PokemonCategory { PokemonId = 36, CategoryId = 7 },
                new PokemonCategory { PokemonId = 37, CategoryId = 3 },
                new PokemonCategory { PokemonId = 38, CategoryId = 3 },
                new PokemonCategory { PokemonId = 39, CategoryId = 7 },
                new PokemonCategory { PokemonId = 40, CategoryId = 7 },
                new PokemonCategory { PokemonId = 41, CategoryId = 2 },
                new PokemonCategory { PokemonId = 42, CategoryId = 2 },
                new PokemonCategory { PokemonId = 43, CategoryId = 1 },
                new PokemonCategory { PokemonId = 44, CategoryId = 1 },
                new PokemonCategory { PokemonId = 45, CategoryId = 1 },
                new PokemonCategory { PokemonId = 46, CategoryId = 6 },
                new PokemonCategory { PokemonId = 47, CategoryId = 6 },
                new PokemonCategory { PokemonId = 48, CategoryId = 6 },
                new PokemonCategory { PokemonId = 49, CategoryId = 6 },
                new PokemonCategory { PokemonId = 50, CategoryId = 9 },
                new PokemonCategory { PokemonId = 51, CategoryId = 9 },
                new PokemonCategory { PokemonId = 52, CategoryId = 7 },
                new PokemonCategory { PokemonId = 53, CategoryId = 7 },
                new PokemonCategory { PokemonId = 54, CategoryId = 5 },
                new PokemonCategory { PokemonId = 55, CategoryId = 5 },
                new PokemonCategory { PokemonId = 56, CategoryId = 10 },
                new PokemonCategory { PokemonId = 57, CategoryId = 10 },
                new PokemonCategory { PokemonId = 58, CategoryId = 3 },
                new PokemonCategory { PokemonId = 59, CategoryId = 3 },
                new PokemonCategory { PokemonId = 60, CategoryId = 5 },
                new PokemonCategory { PokemonId = 61, CategoryId = 5 },
                new PokemonCategory { PokemonId = 62, CategoryId = 5 },
                new PokemonCategory { PokemonId = 63, CategoryId = 11 },
                new PokemonCategory { PokemonId = 64, CategoryId = 11 },
                new PokemonCategory { PokemonId = 65, CategoryId = 11 },
                new PokemonCategory { PokemonId = 66, CategoryId = 10 },
                new PokemonCategory { PokemonId = 67, CategoryId = 10 },
                new PokemonCategory { PokemonId = 68, CategoryId = 10 },
                new PokemonCategory { PokemonId = 69, CategoryId = 1 },
                new PokemonCategory { PokemonId = 70, CategoryId = 1 },
                new PokemonCategory { PokemonId = 71, CategoryId = 1 },
                new PokemonCategory { PokemonId = 72, CategoryId = 5 },
                new PokemonCategory { PokemonId = 73, CategoryId = 5 },
                new PokemonCategory { PokemonId = 74, CategoryId = 12 },
                new PokemonCategory { PokemonId = 75, CategoryId = 12 },
                new PokemonCategory { PokemonId = 76, CategoryId = 12 },
                new PokemonCategory { PokemonId = 77, CategoryId = 3 },
                new PokemonCategory { PokemonId = 78, CategoryId = 3 },
                new PokemonCategory { PokemonId = 79, CategoryId = 5 },
                new PokemonCategory { PokemonId = 80, CategoryId = 5 },
                new PokemonCategory { PokemonId = 81, CategoryId = 8 },
                new PokemonCategory { PokemonId = 82, CategoryId = 8 },
                new PokemonCategory { PokemonId = 83, CategoryId = 7 },
                new PokemonCategory { PokemonId = 84, CategoryId = 7 },
                new PokemonCategory { PokemonId = 85, CategoryId = 7 },
                new PokemonCategory { PokemonId = 86, CategoryId = 5 },
                new PokemonCategory { PokemonId = 87, CategoryId = 5 },
                new PokemonCategory { PokemonId = 88, CategoryId = 2 },
                new PokemonCategory { PokemonId = 89, CategoryId = 2 },
                new PokemonCategory { PokemonId = 90, CategoryId = 5 },
                new PokemonCategory { PokemonId = 91, CategoryId = 5 },
                new PokemonCategory { PokemonId = 92, CategoryId = 14 },
                new PokemonCategory { PokemonId = 93, CategoryId = 14 },
                new PokemonCategory { PokemonId = 94, CategoryId = 14 },
                new PokemonCategory { PokemonId = 95, CategoryId = 12 },
                new PokemonCategory { PokemonId = 96, CategoryId = 11 },
                new PokemonCategory { PokemonId = 97, CategoryId = 11 },
                new PokemonCategory { PokemonId = 98, CategoryId = 5 },
                new PokemonCategory { PokemonId = 99, CategoryId = 5 },
                new PokemonCategory { PokemonId = 100, CategoryId = 8 },
                new PokemonCategory { PokemonId = 101, CategoryId = 8 },
                new PokemonCategory { PokemonId = 102, CategoryId = 1 },
                new PokemonCategory { PokemonId = 103, CategoryId = 1 },
                new PokemonCategory { PokemonId = 104, CategoryId = 9 },
                new PokemonCategory { PokemonId = 105, CategoryId = 9 },
                new PokemonCategory { PokemonId = 106, CategoryId = 10 },
                new PokemonCategory { PokemonId = 107, CategoryId = 10 },
                new PokemonCategory { PokemonId = 108, CategoryId = 7 },
                new PokemonCategory { PokemonId = 109, CategoryId = 2 },
                new PokemonCategory { PokemonId = 110, CategoryId = 2 },
                new PokemonCategory { PokemonId = 111, CategoryId = 9 },
                new PokemonCategory { PokemonId = 112, CategoryId = 9 },
                new PokemonCategory { PokemonId = 113, CategoryId = 7 },
                new PokemonCategory { PokemonId = 114, CategoryId = 1 },
                new PokemonCategory { PokemonId = 115, CategoryId = 7 },
                new PokemonCategory { PokemonId = 116, CategoryId = 5 },
                new PokemonCategory { PokemonId = 117, CategoryId = 5 },
                new PokemonCategory { PokemonId = 118, CategoryId = 5 },
                new PokemonCategory { PokemonId = 119, CategoryId = 5 },
                new PokemonCategory { PokemonId = 120, CategoryId = 5 },
                new PokemonCategory { PokemonId = 121, CategoryId = 5 },
                new PokemonCategory { PokemonId = 122, CategoryId = 11 },
                new PokemonCategory { PokemonId = 123, CategoryId = 6 },
                new PokemonCategory { PokemonId = 124, CategoryId = 13 },
                new PokemonCategory { PokemonId = 125, CategoryId = 8 },
                new PokemonCategory { PokemonId = 126, CategoryId = 3 },
                new PokemonCategory { PokemonId = 127, CategoryId = 6 },
                new PokemonCategory { PokemonId = 128, CategoryId = 7 },
                new PokemonCategory { PokemonId = 129, CategoryId = 5 },
                new PokemonCategory { PokemonId = 130, CategoryId = 5 },
                new PokemonCategory { PokemonId = 131, CategoryId = 5 },
                new PokemonCategory { PokemonId = 132, CategoryId = 7 },
                new PokemonCategory { PokemonId = 133, CategoryId = 7 },
                new PokemonCategory { PokemonId = 134, CategoryId = 5 },
                new PokemonCategory { PokemonId = 135, CategoryId = 8 },
                new PokemonCategory { PokemonId = 136, CategoryId = 3 },
                new PokemonCategory { PokemonId = 137, CategoryId = 7 },
                new PokemonCategory { PokemonId = 138, CategoryId = 12 },
                new PokemonCategory { PokemonId = 139, CategoryId = 12 },
                new PokemonCategory { PokemonId = 140, CategoryId = 12 },
                new PokemonCategory { PokemonId = 141, CategoryId = 12 },
                new PokemonCategory { PokemonId = 142, CategoryId = 12 },
                new PokemonCategory { PokemonId = 143, CategoryId = 7 },
                new PokemonCategory { PokemonId = 144, CategoryId = 13 },
                new PokemonCategory { PokemonId = 145, CategoryId = 8 },
                new PokemonCategory { PokemonId = 146, CategoryId = 3 },
                new PokemonCategory { PokemonId = 147, CategoryId = 15 },
                new PokemonCategory { PokemonId = 148, CategoryId = 15 },
                new PokemonCategory { PokemonId = 149, CategoryId = 15 },
                new PokemonCategory { PokemonId = 150, CategoryId = 11 },
                new PokemonCategory { PokemonId = 151, CategoryId = 11 },
                new PokemonCategory { PokemonId = 1, CategoryId = 2 },
                new PokemonCategory { PokemonId = 2, CategoryId = 2 },
                new PokemonCategory { PokemonId = 3, CategoryId = 2 },
                new PokemonCategory { PokemonId = 6, CategoryId = 4 },
                new PokemonCategory { PokemonId = 12, CategoryId = 4 },
                new PokemonCategory { PokemonId = 13, CategoryId = 2 },
                new PokemonCategory { PokemonId = 14, CategoryId = 2 },
                new PokemonCategory { PokemonId = 15, CategoryId = 2 },
                new PokemonCategory { PokemonId = 16, CategoryId = 4 },
                new PokemonCategory { PokemonId = 17, CategoryId = 4 },
                new PokemonCategory { PokemonId = 18, CategoryId = 4 },
                new PokemonCategory { PokemonId = 21, CategoryId = 4 },
                new PokemonCategory { PokemonId = 22, CategoryId = 4 },
                new PokemonCategory { PokemonId = 31, CategoryId = 9 },
                new PokemonCategory { PokemonId = 34, CategoryId = 9 },
                new PokemonCategory { PokemonId = 41, CategoryId = 4 },
                new PokemonCategory { PokemonId = 42, CategoryId = 4 },
                new PokemonCategory { PokemonId = 43, CategoryId = 2 },
                new PokemonCategory { PokemonId = 44, CategoryId = 2 },
                new PokemonCategory { PokemonId = 45, CategoryId = 2 },
                new PokemonCategory { PokemonId = 46, CategoryId = 1 },
                new PokemonCategory { PokemonId = 47, CategoryId = 1 },
                new PokemonCategory { PokemonId = 48, CategoryId = 2 },
                new PokemonCategory { PokemonId = 49, CategoryId = 2 },
                new PokemonCategory { PokemonId = 62, CategoryId = 10 },
                new PokemonCategory { PokemonId = 69, CategoryId = 2 },
                new PokemonCategory { PokemonId = 70, CategoryId = 2 },
                new PokemonCategory { PokemonId = 71, CategoryId = 2 },
                new PokemonCategory { PokemonId = 72, CategoryId = 2 },
                new PokemonCategory { PokemonId = 73, CategoryId = 2 },
                new PokemonCategory { PokemonId = 74, CategoryId = 9 },
                new PokemonCategory { PokemonId = 75, CategoryId = 9 },
                new PokemonCategory { PokemonId = 76, CategoryId = 9 },
                new PokemonCategory { PokemonId = 79, CategoryId = 11 },
                new PokemonCategory { PokemonId = 80, CategoryId = 11 },
                new PokemonCategory { PokemonId = 83, CategoryId = 4 },
                new PokemonCategory { PokemonId = 84, CategoryId = 4 },
                new PokemonCategory { PokemonId = 85, CategoryId = 4 },
                new PokemonCategory { PokemonId = 87, CategoryId = 13 },
                new PokemonCategory { PokemonId = 91, CategoryId = 13 },
                new PokemonCategory { PokemonId = 92, CategoryId = 2 },
                new PokemonCategory { PokemonId = 93, CategoryId = 2 },
                new PokemonCategory { PokemonId = 94, CategoryId = 2 },
                new PokemonCategory { PokemonId = 95, CategoryId = 9 },
                new PokemonCategory { PokemonId = 102, CategoryId = 11 },
                new PokemonCategory { PokemonId = 103, CategoryId = 11 },
                new PokemonCategory { PokemonId = 111, CategoryId = 12 },
                new PokemonCategory { PokemonId = 112, CategoryId = 12 },
                new PokemonCategory { PokemonId = 121, CategoryId = 11 },
                new PokemonCategory { PokemonId = 123, CategoryId = 4 },
                new PokemonCategory { PokemonId = 124, CategoryId = 11 },
                new PokemonCategory { PokemonId = 130, CategoryId = 4 },
                new PokemonCategory { PokemonId = 131, CategoryId = 13 },
                new PokemonCategory { PokemonId = 138, CategoryId = 5 },
                new PokemonCategory { PokemonId = 139, CategoryId = 5 },
                new PokemonCategory { PokemonId = 140, CategoryId = 5 },
                new PokemonCategory { PokemonId = 141, CategoryId = 5 },
                new PokemonCategory { PokemonId = 142, CategoryId = 4 },
                new PokemonCategory { PokemonId = 144, CategoryId = 4 },
                new PokemonCategory { PokemonId = 145, CategoryId = 4 },
                new PokemonCategory { PokemonId = 146, CategoryId = 4 },
                new PokemonCategory { PokemonId = 149, CategoryId = 4 },
                };
                dataContext.PokemonCategories.AddRange(pokemonCategories);
            }
            // Save changes to the database
            dataContext.SaveChanges();
        }
    }

}


